[target.x86_64-pc-windows-msvc]
linker = "/usr/bin/lld-link-19"
rustflags = [
  "-Lnative=/home/jarek/.xwin/crt/lib/x86_64",
  "-Lnative=/home/jarek/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/jarek/.xwin/sdk/lib/ucrt/x86_64"
]
